name: Keep Supabase Alive

on:
  schedule:
    # 每天UTC时间9点执行（北京时间17点）
    - cron: '0 9 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Keep Supabase alive
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: npm run keep-alive
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "⚠️ Supabase 保活失败!"
        echo "请检查 GitHub Actions 日志获取详细信息"
        echo "访问: https://github.com/${{ github.repository }}/actions"
